function [MF] = monsterMove(pos)
    M = imread('monster.tif');
    MF = figure('units','pixels',...
        'position',pos,...
        'menubar','none',...
        'name','Monster',...
        'numbertitle','off',...
        'resize','off',...
        'keypressfcn',@fh_kpfcn);
    imshow(M);
    set(MF,'position',pos);
    %P = get(MF, 'position');
end